### PR TITLE
liteeth: Add support for 10/100Mbps via SGMII

### PR DESCRIPTION
**Pull request by HarryMakes**
This pull request enables the existing 1000BASE-X PHY implementation to also support 10Mbps and 100Mbps via SGMII. This means the PHY can now automatically detect and operate in any of the following modes (tested on real testbench): 

* 1000Mbps, with 1000BASE-X transceiver
* 1000Mbps, with SGMII transceiver
* 100Mbps, with SGMII transceiver
* 10Mbps, with SGMII transceiver

For further explanation on the implementation, see the full commit message for c0cf664404b7abdbdb1a38e56bae34abdfdee50e.

### CODE REVIEW

**Comment by sbourdeauducq** [comment]
LGTM. Just one detail: the files should say "sgmii" instead of "1000basex". We can do that as a separate PR though, which would also update the targets.

**Comment by HarryMakes** [comment]
Update: 10Mbps has also been tested on a Kasli.

**Comment by sbourdeauducq** [comment]
Good. Please send another PR that does the renaming.

**Comment by HarryMakes** [comment]
@sbourdeauducq Instead of choosing between `sgmii` and `1000basex`, we might also consider `gigabit` to indicate that the PCS implements 2 standards both derived from IEEE 802.3z Gigabit Ethernet. Not sure if this would be confusing in the 10/100Mbps context, however.

**Pull request merged**
