### PR TITLE
bios: added debug info about flashboot source

### PR DESCRIPTION
**Pull request by danielkucera**

### CODE REVIEW

**Comment by danielkucera** [comment]
I was playing with gateware and modifying flash_boot_address but then I realized that the change is not propagated into bios because it was compiled few weeks ago and not recompiling after gateware change. So I added this to see where does bios try to load the firmware from to avoid similar problems and complicated debugging in the future.

**Comment by sbourdeauducq** [comment]
> the change is not propagated into bios because it was compiled few weeks ago and not recompiling after gateware change.

Is that because you didn't reflash it, or because there is a problem with the build system?

**Comment by danielkucera** [comment]
I'm building the flash file on my own from top.bin and bios.bin and if I don't do `rm build/software/bios/*`, bios is not rebuilt automatically

**Comment by sbourdeauducq** [comment]
Then it is a problem with the build system? In that case it should be fixed instead. This problem can pop up in other (and worse) ways instead, e.g. if you change the addresses of the CSRs used by the BIOS for everything (UART etc.).

**Comment by danielkucera** [comment]
probably yes. I'm not denying there is another problem but I think this patch has it's added value and is worth accepting. If you don't agree I have no problem if you refuse it.

**Comment by sbourdeauducq** [comment]
It's generally better to go for the root cause of the problems than accumulate a pile of ad-hoc incomplete solutions.

**Comment by sbourdeauducq** [comment]
OK, then let's fix #91.

**Pull request closed without merging**
